<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vivek" ignored="0" name="RetryMultipleFailedTestCases" tests="5" failures="1" timestamp="21 Mar 2018 05:46:44 GMT" time="0.162" errors="0">
  <testcase name="Test1" time="0.039" classname="com.failedTests.MyTests"/>
  <testcase name="Test2" time="0.004" classname="com.failedTests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="com.failedTests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="com.failedTests.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.003" classname="com.failedTests.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.failedTests.MyTests.Test2(MyTests.java:22)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- RetryMultipleFailedTestCases -->
